import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getProductBySlug, products } from '@wewin/core/fixtures';

import { ConfiguratorIsland } from '@/components/configurator/ConfiguratorIsland';
import { localeBundle } from '@/i18n/server';
import {
  type LocaleRouteParams,
  languageAlternates,
  localeFromSegment,
  localeHref,
} from '@/lib/routing';

/**
 * `/[locale]/products/[slug]` — the configurator page.
 *
 * This file is the **server half**: which product, whether it exists, what goes in the
 * `<head>`, and the one `<main>` the island hangs from. Everything from the first
 * interactive control inward is `ConfiguratorIsland`, which plan 8.1 requires to be a
 * single client island and which this round did not split.
 *
 * 8 locales × 81 products = **648 prerendered pages**, which is the entire return on
 * phase 6b. Everything unusual about this file is in service of keeping them prerendered.
 */

/** The `[slug]` half of the 648. `[locale]` is generated by the layout above. */
export function generateStaticParams(): { slug: string }[] {
  return products.map((product) => ({ slug: product.slug }));
}

/**
 * The set of products is closed at build time, exactly as the set of locales is.
 *
 * Stated here rather than left to inherit from the layout. With `false`, a request for
 * `/th/products/does-not-exist` is answered by the router; with the default, Next would
 * render this segment on demand for any slug, and every typo'd or stale URL would become
 * a function invocation that ends in the `notFound()` below. Same answer, paid for.
 */
export const dynamicParams = false;

/**
 * `params`, and **never `searchParams`** — plan 8.2's second trap, and this is the route
 * where it would have been tempting.
 *
 * A share link is `?width=…&height=…&v=3`, so "the metadata should describe the shared
 * configuration" is a perfectly reasonable-sounding sentence. Acting on it reads
 * `searchParams` here, which opts all 648 pages out of static rendering silently — no
 * prerender, no ISR, a function invocation per request, and no error anywhere to say so.
 *
 * The choice, stated: **the metadata describes the product, not the configuration.** A
 * crawler indexes the product; the query string is read in the browser by the island and
 * nowhere else (see `state/useUrlSearch.ts`, which is why `useSearchParams` is not used
 * either). `tests/cache-policy.test.ts` scans for a `searchParams` reaching a
 * `generateMetadata` and fails the suite if one does.
 */
export async function generateMetadata({
  params,
}: {
  readonly params: Promise<LocaleRouteParams & { readonly slug: string }>;
}): Promise<Metadata> {
  const { locale: segment, slug } = await params;
  const locale = localeFromSegment(segment);
  if (locale === null) notFound();

  const product = getProductBySlug(slug);
  if (!product) notFound();

  // `localeBundle` and not `useLocale()`: this runs on the server, where there is no
  // provider and no hooks. Same six fields, minus `setLocale` — see `i18n/server.ts`.
  const { t, content } = localeBundle(locale);

  // The product's own name and summary, in this locale where a catalogue has one and in
  // Thai where it has not. `content` reports which happened; a `<title>` cannot carry a
  // `lang` marker, so what it can do instead is be honest about the language of the
  // *page*, which `<html lang>` in the root layout already is.
  const name = content({ on: 'productName', productId: product.id }, product.nameTh);
  const summary = content({ on: 'productSummary', productId: product.id }, product.summaryTh);

  const path = `/products/${product.slug}`;

  return {
    // Slots into the layout's `%s · WEWIN180` template.
    title: name.text,
    description: `${summary.text} · ${t('meta.description')}`,
    alternates: {
      canonical: localeHref(locale, path),
      // Eight `hreflang`s keyed by ICU tag plus `x-default → /th`. Per route, because
      // metadata set in a layout is inherited and would give all 648 pages one canonical.
      languages: languageAlternates(path),
    },
  };
}

export default async function ProductConfiguratorPage({
  params,
}: {
  readonly params: Promise<LocaleRouteParams & { readonly slug: string }>;
}) {
  const { locale: segment, slug } = await params;
  const locale = localeFromSegment(segment);
  if (locale === null) notFound();

  // Verified here, on the server, so an unknown slug is a 404 rather than a page that
  // renders an empty configurator. The island looks the product up again from the same
  // fixtures rather than being handed it: only strings cross the boundary, because a
  // `Product` holds `bigint` micrometres and `bigint` satang and a serialiser is not a
  // thing to trust with either.
  if (!getProductBySlug(slug)) notFound();

  return (
    <main className="container-page py-6 md:py-8 lg:py-10">
      <ConfiguratorIsland locale={locale} slug={slug} />
    </main>
  );
}
