import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getProductBySlug, products } from '@wewin/core/fixtures';

import { ConfiguratorIsland } from '@/components/configurator/ConfiguratorIsland';
import {
  loadPublishedProduct,
  loadPublishedProductById,
  type PublishedProduct,
} from '@/lib/catalog/published-product';
import { ProductGallery } from '@/components/catalog/ProductGallery';
import { ReviewBlock } from '@/components/reviews/ReviewBlock';
import { localeBundle } from '@/i18n/server';
import {
  type LocaleRouteParams,
  languageAlternates,
  localeFromSegment,
  localeHref,
} from '@/lib/routing';

/**
 * `/[locale]/products/[slug]` — the configurator page.
 *
 * This file is the **server half**: which product, whether it exists, what goes in the
 * `<head>`, and the one `<main>` the island hangs from. Everything from the first
 * interactive control inward is `ConfiguratorIsland`, which plan 8.1 requires to be a
 * single client island and which this round did not split.
 *
 * 8 locales × 81 products = **648 prerendered pages**, which is the entire return on
 * phase 6b. Everything unusual about this file is in service of keeping them prerendered.
 */

/** The `[slug]` half of the 648. `[locale]` is generated by the layout above. */
export function generateStaticParams(): { slug: string }[] {
  return products.map((product) => ({ slug: product.slug }));
}

/**
 * ⭐ The set of products is **no longer closed at build time**, and that is the whole point.
 *
 * It used to be `false`, with a good argument: a typo'd URL was answered by the router
 * instead of becoming a function invocation that ends in `notFound()`. What that argument
 * did not account for is that the build enumerates `@wewin/core/fixtures`, so a product
 * created in the dashboard — published, correct, and served by the API — was answered 404 by
 * the shop forever. Verified before this change on two dashboard-created products, one of
 * them months old.
 *
 * ⚠️ The cost is real and is the one the old comment named: a stale or typo'd URL now costs
 * one invocation and one API call before its 404. It is the smaller cost. A shop that cannot
 * sell what its own back office creates is not trading; a wasted request is a wasted request.
 *
 * The 81 fixture products are unaffected — they are still enumerated by
 * `generateStaticParams` below and still prerendered, with no fetch on their path.
 */
export const dynamicParams = true;

/**
 * `params`, and **never `searchParams`** — plan 8.2's second trap, and this is the route
 * where it would have been tempting.
 *
 * A share link is `?width=…&height=…&v=3`, so "the metadata should describe the shared
 * configuration" is a perfectly reasonable-sounding sentence. Acting on it reads
 * `searchParams` here, which opts all 648 pages out of static rendering silently — no
 * prerender, no ISR, a function invocation per request, and no error anywhere to say so.
 *
 * The choice, stated: **the metadata describes the product, not the configuration.** A
 * crawler indexes the product; the query string is read in the browser by the island and
 * nowhere else (see `state/useUrlSearch.ts`, which is why `useSearchParams` is not used
 * either). `tests/cache-policy.test.ts` scans for a `searchParams` reaching a
 * `generateMetadata` and fails the suite if one does.
 */
export async function generateMetadata({
  params,
}: {
  readonly params: Promise<LocaleRouteParams & { readonly slug: string }>;
}): Promise<Metadata> {
  const { locale: segment, slug } = await params;
  const locale = localeFromSegment(segment);
  if (locale === null) notFound();

  /*
   * ⚠️ Fixtures first, and no fetch when they answer. The 81 keep a metadata path with no
   * network on it — which is what lets `tests/configurator-render.test.ts` call this in an
   * environment that has no fetch stub — and only a slug they do not know pays for a request.
   */
  const identity = await identify(slug);
  if (identity === null) notFound();

  // `localeBundle` and not `useLocale()`: this runs on the server, where there is no
  // provider and no hooks. Same six fields, minus `setLocale` — see `i18n/server.ts`.
  const { t, content } = localeBundle(locale);

  // The product's own name and summary, in this locale where a catalogue has one and in
  // Thai where it has not. `content` reports which happened; a `<title>` cannot carry a
  // `lang` marker, so what it can do instead is be honest about the language of the
  // *page*, which `<html lang>` in the root layout already is.
  //
  // ⚠️ A dashboard-created product has no entry in the compiled translation bundles, so
  // `content` falls back to Thai for it. That is correct and not a gap to paper over: there
  // is no translation, and inventing one would be worse than showing the language it was
  // written in.
  const name = content({ on: 'productName', productId: identity.id }, identity.nameTh);
  const summary = content({ on: 'productSummary', productId: identity.id }, identity.summaryTh);

  const path = `/products/${identity.slug}`;

  return {
    // Slots into the layout's `%s · WEWIN180` template.
    title: name.text,
    description: `${summary.text} · ${t('meta.description')}`,
    alternates: {
      canonical: localeHref(locale, path),
      // Eight `hreflang`s keyed by ICU tag plus `x-default → /th`. Per route, because
      // metadata set in a layout is inherited and would give all 648 pages one canonical.
      languages: languageAlternates(path),
    },
  };
}

export default async function ProductConfiguratorPage({
  params,
}: {
  readonly params: Promise<LocaleRouteParams & { readonly slug: string }>;
}) {
  const { locale: segment, slug } = await params;
  const locale = localeFromSegment(segment);
  if (locale === null) notFound();

  // Verified here, on the server, so an unknown slug is a 404 rather than a page that
  // renders an empty configurator. For a fixture product the island still looks it up by
  // slug from the same compiled data — only strings cross the boundary, because a `Product`
  // holds `bigint` micrometres and `bigint` satang and a serialiser is not a thing to trust
  // with either. A product that is in no bundle is handed its published **document**, whose
  // quantities are tagged digit strings, so that property survives.
  const identity = await identify(slug);
  if (identity === null) notFound();

  /*
   * ⛔ Everything below is handed `identity.slug`, never the raw `[slug]` segment.
   *
   * That segment can be a product **id** — the page resolves those too, so a cart line or a
   * bookmark written before slugs were recorded still opens. But the children do real work
   * with it: `ProductGallery` fetches `/catalog/products/<it>`, and the island looks the
   * product up in the fixtures and builds share links from it. Passing the segment straight
   * through meant a product reached by its id rendered with **no photographs at all**,
   * because that fetch 404'd. Seen in a screenshot, not by any test.
   */
  return (
    <main className="container-page py-6 md:py-8 lg:py-10">
      {/*
        ⭐ The gallery is handed to the island rather than rendered above it, so it lands in
        the sticky left column beside the drawing. As a sibling it filled a laptop screen on
        its own and pushed the name, the size boxes and the price below the fold.

        Still a server component — only the already-rendered element crosses the boundary.
      */}
      <ConfiguratorIsland
        locale={locale}
        slug={identity.slug}
        document={identity.document}
        gallery={<ProductGallery slug={identity.slug} productId={identity.id} locale={locale} />}
      />
      {/*
        The reviews — plan section 9, and the first thing on this storefront that comes
        from a fetch rather than from `@wewin/core/fixtures`.

        It renders **nothing at all** unless this product has a visible review, which today
        and for months means nothing at all on all 648 pages (plan 9.5: do not print "no
        reviews yet" 81 times). The fetch inside it is `force-cache` + tagged, so the page
        stays prerendered and a published review reaches it through
        `revalidateTag` — `src/app/api/revalidate/route.ts` is the other half, and it
        landed in this same commit because an invalidation endpoint nothing calls is worse
        than none.

        `product.id` and not `slug`: the tag, the API path and `product_review_stats` are
        all keyed by the catalogue's product id, and a page that invalidated one spelling
        while the writer poked the other would never update and never say why.
      */}
      <ReviewBlock productId={identity.id} locale={locale} />
    </main>
  );
}

/**
 * Which product this slug names — from the compiled catalogue if it is in there, from the
 * database if it is not.
 *
 * ⛔ Fixtures are tried first and the order is load-bearing, not a preference. It keeps the
 * 81 prerendered pages on a path with no network: no fetch during the build, none in
 * `generateMetadata`, and byte-identical output. Only a slug the bundle does not know pays
 * for a request, which is exactly the set of products that could not be shown at all before.
 */
async function identify(slug: string): Promise<{
  readonly id: string;
  readonly slug: string;
  readonly nameTh: string;
  readonly summaryTh: string;
  /** Present only for a product that came from the database — see `ConfiguratorIsland`. */
  readonly document?: PublishedProduct['wire'] | undefined;
} | null> {
  const fixture = getProductBySlug(slug);
  if (fixture) {
    return {
      id: fixture.id,
      slug: fixture.slug,
      nameTh: fixture.nameTh,
      summaryTh: fixture.summaryTh,
    };
  }

  const published = await loadPublishedProduct(slug);
  /*
   * ⭐ Then by **id**, because links built from one exist in the wild: a cart line saved
   * before `QuoteLine.productSlug` existed, a bookmark, a pasted message. Each of those used
   * to answer 404 · ไม่พบหน้านี้, which reads as "this product is gone".
   *
   * ⚠️ Second, never first. A slug is what this route is for, and checking it first means a
   * product whose *slug* happens to equal another product's *id* still resolves to the one
   * the URL is actually naming.
   */
  const found = published ?? (await loadPublishedProductById(slug));
  if (found === null) return null;

  return {
    id: found.productId,
    slug: found.slug,
    nameTh: found.nameTh,
    summaryTh: found.summaryTh,
    document: found.wire,
  };
}
