-- Reviews, review photos and the per-user profile — plan sections 9 and 4.1/4.2.
--
-- Generated by drizzle-kit from src/schema/review.ts and src/schema/profile.ts, with ONE
-- statement added by hand at the top. The rules that are not tables — the delivered-order
-- guard, the append-only write guard, the EXIF/erasure paths, `review_is_public()` and the
-- two views — are in 0020_review_guards.sql, the same arrangement 0007 and 0011 use.
--
-- ── The hand-added statement, and why it is not in quote.ts ──────────────────────
--
-- `reviews_line_version_fk` proves two things at once (see the block comment in review.ts):
-- that the catalogue version a review names is that line's own, and — because a `freeform`
-- line has a NULL `product_version_id` and so cannot satisfy a foreign key from a NOT NULL
-- column — that the line is a `catalog` line. A delivery charge is therefore unreviewable
-- by referential integrity rather than by a trigger.
--
-- A composite foreign key needs a UNIQUE on the parent columns, and this one is a constraint
-- on `quote_lines`, a table phase 5c owns. Declaring it in quote.ts would put a constraint
-- that exists solely for this file into that file's list of invariants, where the next
-- reader would have to guess what it is for. It is redundant as a uniqueness claim — `id` is
-- already the primary key — and load-bearing purely as a foreign-key target, which is
-- exactly what `order_events_id_order_key` says about itself in order.ts.
--
-- NULLs are distinct in a unique index by default, so this adds no constraint at all to the
-- free-form lines that carry no version, and it can never fail on existing data.
ALTER TABLE "quote_lines"
  ADD CONSTRAINT "quote_lines_id_product_version_key" UNIQUE ("id", "product_version_id");
--> statement-breakpoint
CREATE TABLE "review_photos" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"review_id" uuid NOT NULL,
	"seq" integer NOT NULL,
	"storage_key" text,
	"storage_key_erased_at" timestamp with time zone,
	"content_type" text NOT NULL,
	"byte_size" bigint NOT NULL,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"checksum_sha256" char(64) NOT NULL,
	"source_checksum_sha256" char(64) NOT NULL,
	"strip_recipe" text NOT NULL,
	"alt_text_th" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "review_photos_storage_key_unique" UNIQUE("storage_key"),
	CONSTRAINT "review_photos_review_seq_key" UNIQUE("review_id","seq"),
	CONSTRAINT "review_photos_seq_positive" CHECK ("review_photos"."seq" >= 1),
	CONSTRAINT "review_photos_content_type_supported" CHECK ("review_photos"."content_type" in ('image/jpeg', 'image/png', 'image/webp')),
	CONSTRAINT "review_photos_byte_size_positive" CHECK ("review_photos"."byte_size" > 0),
	CONSTRAINT "review_photos_dimensions_positive" CHECK ("review_photos"."width" > 0 and "review_photos"."height" > 0),
	CONSTRAINT "review_photos_checksum_hex" CHECK ("review_photos"."checksum_sha256" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "review_photos_source_checksum_hex" CHECK ("review_photos"."source_checksum_sha256" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "review_photos_bytes_were_rewritten" CHECK ("review_photos"."checksum_sha256" <> "review_photos"."source_checksum_sha256"),
	CONSTRAINT "review_photos_strip_recipe_present" CHECK (btrim("review_photos"."strip_recipe") <> ''),
	CONSTRAINT "review_photos_erasure_shape" CHECK ("review_photos"."storage_key_erased_at" is null or "review_photos"."storage_key" is null)
);
--> statement-breakpoint
CREATE TABLE "reviews" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"order_id" uuid NOT NULL,
	"quote_line_id" uuid NOT NULL,
	"product_version_id" uuid NOT NULL,
	"rating" smallint NOT NULL,
	"body_th" text,
	"author_display_name" text,
	"author_user_id" uuid,
	"author_guest_id" uuid,
	"content_erased_at" timestamp with time zone,
	"moderation_window_hours" integer NOT NULL,
	"published_at" timestamp with time zone,
	"published_by_user_id" uuid,
	"hidden_at" timestamp with time zone,
	"hidden_by_user_id" uuid,
	"hidden_reason" text,
	"hidden_note_th" text,
	"reply_th" text,
	"replied_by_user_id" uuid,
	"replied_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "reviews_line_key" UNIQUE("quote_line_id"),
	CONSTRAINT "reviews_rating_range" CHECK ("reviews"."rating" between 1 and 5),
	CONSTRAINT "reviews_moderation_window_bounded" CHECK ("reviews"."moderation_window_hours" between 1 and 720),
	CONSTRAINT "reviews_author_shape" CHECK (num_nonnulls("reviews"."author_user_id", "reviews"."author_guest_id") = 1),
	CONSTRAINT "reviews_body_not_blank" CHECK ("reviews"."body_th" is null or btrim("reviews"."body_th") <> ''),
	CONSTRAINT "reviews_content_erasure_shape" CHECK ("reviews"."content_erased_at" is null
          or ("reviews"."body_th" is null and "reviews"."author_display_name" is null)),
	CONSTRAINT "reviews_hidden_shape" CHECK (num_nonnulls("reviews"."hidden_at", "reviews"."hidden_by_user_id", "reviews"."hidden_reason") in (0, 3)),
	CONSTRAINT "reviews_hidden_reason_known" CHECK ("reviews"."hidden_reason" is null or "reviews"."hidden_reason" in ('abusive', 'personal_data', 'off_topic', 'spam', 'other')),
	CONSTRAINT "reviews_hidden_other_needs_a_note" CHECK ("reviews"."hidden_reason" is distinct from 'other'
          or btrim(coalesce("reviews"."hidden_note_th", '')) <> ''),
	CONSTRAINT "reviews_hidden_note_needs_a_hiding" CHECK ("reviews"."hidden_note_th" is null or "reviews"."hidden_at" is not null),
	CONSTRAINT "reviews_published_shape" CHECK (num_nonnulls("reviews"."published_at", "reviews"."published_by_user_id") in (0, 2)),
	CONSTRAINT "reviews_reply_shape" CHECK (num_nonnulls("reviews"."reply_th", "reviews"."replied_by_user_id", "reviews"."replied_at") in (0, 3)),
	CONSTRAINT "reviews_reply_not_blank" CHECK ("reviews"."reply_th" is null or btrim("reviews"."reply_th") <> ''),
	CONSTRAINT "reviews_moderation_after_creation" CHECK (("reviews"."published_at" is null or "reviews"."published_at" >= "reviews"."created_at")
          and ("reviews"."hidden_at" is null or "reviews"."hidden_at" >= "reviews"."created_at")
          and ("reviews"."replied_at" is null or "reviews"."replied_at" >= "reviews"."created_at"))
);
--> statement-breakpoint
CREATE TABLE "user_preferences" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"preferred_locale" text,
	"display_currency" char(3),
	"display_length_unit" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_preferences_says_something" CHECK (num_nonnulls("user_preferences"."preferred_locale", "user_preferences"."display_currency", "user_preferences"."display_length_unit") >= 1),
	CONSTRAINT "user_preferences_locale_shape" CHECK ("user_preferences"."preferred_locale" is null or "user_preferences"."preferred_locale" ~ '^[a-z]{2}(-[A-Za-z0-9]{2,8})?$'),
	CONSTRAINT "user_preferences_currency_known" CHECK ("user_preferences"."display_currency" is null or "user_preferences"."display_currency" in ('CNY', 'EUR', 'INR', 'LAK', 'MYR', 'SGD', 'THB', 'USD', 'VND')),
	CONSTRAINT "user_preferences_length_unit_known" CHECK ("user_preferences"."display_length_unit" is null or "user_preferences"."display_length_unit" in ('mm', 'cm', 'm', 'in', 'ft'))
);
--> statement-breakpoint
ALTER TABLE "review_photos" ADD CONSTRAINT "review_photos_review_id_reviews_id_fk" FOREIGN KEY ("review_id") REFERENCES "public"."reviews"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_product_version_id_product_versions_id_fk" FOREIGN KEY ("product_version_id") REFERENCES "public"."product_versions"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_author_user_id_users_id_fk" FOREIGN KEY ("author_user_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_author_guest_id_guests_id_fk" FOREIGN KEY ("author_guest_id") REFERENCES "public"."guests"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_published_by_user_id_users_id_fk" FOREIGN KEY ("published_by_user_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_hidden_by_user_id_users_id_fk" FOREIGN KEY ("hidden_by_user_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_replied_by_user_id_users_id_fk" FOREIGN KEY ("replied_by_user_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_line_fk" FOREIGN KEY ("quote_line_id","order_id") REFERENCES "public"."quote_lines"("id","order_id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_line_version_fk" FOREIGN KEY ("quote_line_id","product_version_id") REFERENCES "public"."quote_lines"("id","product_version_id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user_preferences" ADD CONSTRAINT "user_preferences_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "review_photos_review_idx" ON "review_photos" USING btree ("review_id","seq");--> statement-breakpoint
CREATE INDEX "reviews_version_idx" ON "reviews" USING btree ("product_version_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "reviews_order_idx" ON "reviews" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "reviews_moderation_queue_idx" ON "reviews" USING btree ("created_at") WHERE published_at is null and hidden_at is null;--> statement-breakpoint
CREATE INDEX "reviews_author_idx" ON "reviews" USING btree ("author_user_id") WHERE author_user_id is not null;